id: I89BD2426
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T19:14:19+00:00'
last_modified: '2022-06-07T12:07:20.915077+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3712
  title: བློ་སྦྱོང་ལེགས་བཤད་ཀུན་འདུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    04F4:
      image_group_id: I1KG3799
      title: Volume 1 of blo sbyong legs bshad kun 'dus
      total_pages: 252
      order: 1
      base_file: 04F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
